name: Run Discord Bot

on:
  schedule:
    - cron: "0 */6 * * *"   # Her 6 saatte bir çalışır
  workflow_dispatch:        # Manuel başlatma

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run bot
        run: |
          node launcher.js &
          sleep 21600   # 6 saat çalıştır (21600 sn)
